export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const EVENTS_REPOSITORY = 'EVENTS_REPOSITORY';
export const SEATS_REPOSITORY = 'SEATS_REPOSITORY';
export const BOOKINGS_REPOSITORY = 'BOOKINGS_REPOSITORY';
export const PAYMENTS_REPOSITORY = 'PAYMENTS_REPOSITORY';
export const PASSWORD_SERVICE = 'PASSWORD_SERVICE';
export const TOKEN_SERVICE = 'TOKEN_SERVICE';
export const PAYMENT_PROCESSOR = 'PAYMENT_PROCESSOR';